// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetData, GetResponses, DeleteTasksByIdData, DeleteTasksByIdResponses, GetTasksByIdData, GetTasksByIdResponses, PutTasksByIdData, PutTasksByIdResponses, GetTasksData, GetTasksResponses, PostTasksData, PostTasksResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Hello World
 */
export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Delete a task by ID
 */
export const deleteTasksById = <ThrowOnError extends boolean = false>(options: Options<DeleteTasksByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteTasksByIdResponses, unknown, ThrowOnError>({
        url: '/tasks/{id}',
        ...options
    });
};

/**
 * Get a task by ID
 */
export const getTasksById = <ThrowOnError extends boolean = false>(options: Options<GetTasksByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTasksByIdResponses, unknown, ThrowOnError>({
        url: '/tasks/{id}',
        ...options
    });
};

/**
 * Update a task by ID
 */
export const putTasksById = <ThrowOnError extends boolean = false>(options: Options<PutTasksByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutTasksByIdResponses, unknown, ThrowOnError>({
        url: '/tasks/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get all tasks
 */
export const getTasks = <ThrowOnError extends boolean = false>(options?: Options<GetTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTasksResponses, unknown, ThrowOnError>({
        url: '/tasks',
        ...options
    });
};

/**
 * Create a new task
 */
export const postTasks = <ThrowOnError extends boolean = false>(options: Options<PostTasksData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostTasksResponses, unknown, ThrowOnError>({
        url: '/tasks',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};