// This file is auto-generated by @hey-api/openapi-ts

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteTasksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type DeleteTasksByIdResponses = {
    /**
     * Default Response
     */
    204: void;
};

export type DeleteTasksByIdResponse = DeleteTasksByIdResponses[keyof DeleteTasksByIdResponses];

export type GetTasksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type GetTasksByIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: number;
        title: string;
        status: number;
    }>;
};

export type GetTasksByIdResponse = GetTasksByIdResponses[keyof GetTasksByIdResponses];

export type PutTasksByIdData = {
    body: {
        title: string;
        status: number;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type PutTasksByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: number;
        title: string;
        status: number;
    };
};

export type PutTasksByIdResponse = PutTasksByIdResponses[keyof PutTasksByIdResponses];

export type GetTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type GetTasksResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: number;
        title: string;
        status: number;
    }>;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type PostTasksData = {
    body: {
        title: string;
    };
    path?: never;
    query?: never;
    url: '/tasks';
};

export type PostTasksResponses = {
    /**
     * Default Response
     */
    201: {
        id: number;
        title: string;
        status: number;
    };
};

export type PostTasksResponse = PostTasksResponses[keyof PostTasksResponses];

export type ClientOptions = {
    baseUrl: 'http://192.168.163.212:3000' | (string & {});
};